apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - vault-serviceaccount.yaml
  - vault-configmap.yaml
  - vault-statefulset.yaml
  - vault-service.yaml
  - vault-init-job.yaml
  - vault-unseal-job.yaml

images:
  - name: hashicorp/vault
    newName: hashicorp/vault
    newTag: 1.15.0

namespace: vault