apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Chart.yaml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.25.0
    valuesFile: values.yaml
    releaseName: vault
    namespace: vault