apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: TCP
    - name: internal-cluster
      port: {{ .Values.service.ports.cluster.port }}
      targetPort: {{ .Values.service.ports.cluster.targetPort }}
      protocol: TCP
  selector:
    {{- include "vault.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: TCP
  selector:
    {{- include "vault.selectorLabels" . | nindent 4 }}